# Generated by Django 3.1.2 on 2020-10-28 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('age', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=255)),
                ('citizenship_number', models.PositiveIntegerField()),
                ('home_phone_number', models.PositiveIntegerField()),
                ('emp_code', models.IntegerField(default=0)),
                ('joined_date', models.DateField()),
                ('department', models.CharField(max_length=55)),
                ('position', models.CharField(max_length=55)),
                ('salary', models.PositiveBigIntegerField(default=9999)),
                ('bio', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='images/')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.gender')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.status')),
            ],
        ),
    ]
