# Generated by Django 3.1.2 on 2020-11-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_employee_national_certificate_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(default='', max_length=55),
        ),
        migrations.AlterField(
            model_name='employee',
            name='home_phone_number',
            field=models.PositiveIntegerField(default=''),
        ),
    ]
